{% set name = "django-htmx" %}
{% set version = "1.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7306e1aba4e407496f30a57ec2e0b2974a9b96c8c6036f7ec6a8b5753ea0abdd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2
    - asgiref >=3.6

test:
  imports:
    - django_htmx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/django-htmx
  doc_url: https://django-htmx.readthedocs.io/
  summary: Extensions for using Django with htmx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
