{% set name = "django-htmx" %}
{% set version = "1.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6a97ff0256a247a2c20c85c1f81358fa0c9650af52e6064cb6664ae8619c9294

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - django >=3.2

test:
  imports:
    - django_htmx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-htmx
  doc_url: https://django-htmx.readthedocs.io/
  summary: Extensions for using Django with htmx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
