{% set name = "django-htmx" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 71e6242ac6bd32a0e14fcb12b340f901c9a924f0b4e9b461a5e6a6eea8d9c6dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2
    - asgiref >=3.6

test:
  imports:
    - django_htmx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/django-htmx
  doc_url: https://django-htmx.readthedocs.io/
  summary: Extensions for using Django with htmx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
