{% set name = "django-htmx" %}
{% set version = "1.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b689a8d6f7052a96a373411ec55ba81c1ddffb4d66b1f5ab4d6e3d28420842fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - django >=3.2

test:
  imports:
    - django_htmx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/django-htmx
  doc_url: https://django-htmx.readthedocs.io/
  summary: Extensions for using Django with htmx.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
