schema_version: 1

context:
  name: django-htmx
  version: "1.26.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 88ecc2f8a3f13ad5a50e6b16be127f04fba369124cc40a09b21ce33babb04aa6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=77
  run:
    - python >=${{ python_min }}
    - django >=4.2
    - asgiref >=3.6

tests:
  - python:
      imports:
        - django_htmx
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Extensions for using Django with htmx.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/adamchainz/django-htmx
  documentation: https://django-htmx.readthedocs.io/

extra:
  recipe-maintainers:
    - thewchan
